### PR TITLE
Permit arguments for `barnyard always`.

### PR DESCRIPTION
**Pull request by allspiritseve**
Definitely open to suggestions on this, just figured I'd try my hand at implementing arguments for `barnyard_run_`. I'm not sure what the regex to detect a module should look like, so for testing purposes it is currently looking for a file ending in `.zsh`.

### CODE REVIEW

**Comment by flatheadmill** [comment]
And so, it would seem that we're going to assume that `*.zsh` is a program and we're going to stop interpreting arguments to `barnyard always` once we reach a none `*.zsh` or `--` and that kind of makes sense. We could insist that the user run programs one at a time, though. It was kind of a nice to have to not have to checkout the work on each module, to have multiple modules run on a single invocation of `always`, but now that is making for some goofy command line parsing.

If we get rid of multiple modules, then command line interpretation is simple.

Within a Barnyard invocation, the `barnyard_always` function uses the current working extract on each call so it's only Zsh function call overhead, not `git extract` overhead.

Also, when using `--barnyard=../my-barnyard` we do not do an extract, we just use the given directory. We only do an extract when using the system barnyard.

And so...

Makes more sense to get rid of run a batch of modules and then have deathly simple argument parsing.

And then removed the ambiguity. We only have one barnyard module for which we want to pass arguments, but the moment we have two we couldn't call them multi-module. Who's argument are we going to use? Let's not conjure on the concept of consuming arguments and leaving remainders, or using multiple `--` (which kind of wouldn't work, because then `--` itself is can never be an argument.

Leaning toward one module at a time for `always`. The invocation on a production machine, yes I do it, but never multi-module style. When you're working on a production machine you should never be in a milliseconds hurry.

**Comment by allspiritseve** [comment]
@flatheadmill updated to permit command line arguments for `barnyard always` calls. We now permit a single module per instance of `barnyard always` and the remainder of the command line arguments are forwarded to the executed program.

**Comment by flatheadmill** [comment]
Does this work with the `barnyard_always` function?

**Comment by allspiritseve** [comment]
I'll test it.

**Comment by allspiritseve** [comment]
@flatheadmill yes it works with `barnyard_apply`.

**Review by flatheadmill — APPROVED** [review]

**Pull request merged**
